name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 💿 Install Dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_server_dir }}
          exclude: .git*
            - **.git*
            - .git*/**
            -  **/.git*/**
            - **.github*
            - .github*/**
            -  **/.github*/**
            - node_modules/**
            - node_modules/**/*
